"use client";

import { ArrowRight, CheckCircle2, FileText, HelpCircle } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { EmptyState } from "@/components/empty-state";
import type { Meeting } from "@/lib/types";

export function NotesPanel({ meeting }: { meeting: Meeting }) {
  const notes = meeting.notes;
  if (!notes) {
    return (
      <EmptyState
        icon={FileText}
        title="No notes generated yet"
        description="Paste a transcript and click Generate notes to extract decisions, action items, and open questions."
      />
    );
  }

  const confidencePct = Math.round((notes.confidence || 0) * 100);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Executive summary</CardTitle>
            <p className="text-xs text-muted-foreground">
              {notes.used_mock ? "Generated with the mock provider" : `Generated by ${notes.model_name}`}
            </p>
          </div>
          <div className="flex flex-col items-end gap-2 min-w-[140px]">
            <span className="text-xs text-muted-foreground">Confidence</span>
            <Progress value={confidencePct} className="h-1.5" />
            <span className="text-sm font-medium">{confidencePct}%</span>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed text-foreground/90">{notes.executive_summary}</p>
        </CardContent>
      </Card>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-success" />
              <CardTitle>Key decisions</CardTitle>
              <Badge variant="muted" className="ml-auto">{notes.key_decisions.length}</Badge>
            </div>
          </CardHeader>
          <CardContent>
            {notes.key_decisions.length === 0 ? (
              <p className="text-sm text-muted-foreground">No decisions captured.</p>
            ) : (
              <ul className="space-y-3">
                {notes.key_decisions.map((d, i) => (
                  <li key={i} className="flex gap-3 text-sm leading-snug">
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-success" />
                    {d}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <HelpCircle className="h-4 w-4 text-warning" />
              <CardTitle>Open questions</CardTitle>
              <Badge variant="muted" className="ml-auto">{notes.unresolved_questions.length}</Badge>
            </div>
          </CardHeader>
          <CardContent>
            {notes.unresolved_questions.length === 0 ? (
              <p className="text-sm text-muted-foreground">No unresolved questions.</p>
            ) : (
              <ul className="space-y-3">
                {notes.unresolved_questions.map((q, i) => (
                  <li key={i} className="flex gap-3 text-sm leading-snug">
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-warning" />
                    {q}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      {notes.suggested_follow_up ? (
        <Card className="border-primary/30 bg-primary/5">
          <CardContent className="flex items-start gap-3 p-5">
            <ArrowRight className="mt-0.5 h-4 w-4 text-primary" />
            <div>
              <p className="text-xs font-medium uppercase tracking-wide text-primary">Suggested follow-up</p>
              <p className="mt-1 text-sm">{notes.suggested_follow_up}</p>
            </div>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}
