from __future__ import annotations

import re
from datetime import datetime

from app.models.action_item import ActionItemStatus
from app.models.meeting import Meeting
from app.schemas.meeting import MarkdownExport


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or "meeting"


def _fmt_date(value: datetime | None) -> str:
    if not value:
        return "—"
    return value.strftime("%Y-%m-%d %H:%M UTC")


def export_meeting(meeting: Meeting) -> MarkdownExport:
    lines: list[str] = []
    lines.append(f"# {meeting.title}")
    lines.append("")
    lines.append(f"- **Date:** {_fmt_date(meeting.meeting_date)}")
    lines.append(f"- **Participants:** {meeting.participants or '—'}")
    lines.append(f"- **Status:** {meeting.status.value}")
    lines.append("")

    notes = meeting.notes
    if notes:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(notes.executive_summary or "_No summary available._")
        lines.append("")

        lines.append("## Key Decisions")
        lines.append("")
        if notes.key_decisions:
            for d in notes.key_decisions:
                lines.append(f"- {d}")
        else:
            lines.append("_No decisions recorded._")
        lines.append("")

        lines.append("## Action Items")
        lines.append("")
        if meeting.action_items:
            for item in meeting.action_items:
                check = "x" if item.status == ActionItemStatus.COMPLETED else " "
                owner = f" — _owner:_ **{item.owner}**" if item.owner else ""
                due = f" — _due:_ {_fmt_date(item.due_date)}" if item.due_date else ""
                lines.append(f"- [{check}] {item.description}{owner}{due}")
        else:
            lines.append("_No action items._")
        lines.append("")

        lines.append("## Unresolved Questions")
        lines.append("")
        if notes.unresolved_questions:
            for q in notes.unresolved_questions:
                lines.append(f"- {q}")
        else:
            lines.append("_No open questions._")
        lines.append("")

        lines.append("## Suggested Follow-up")
        lines.append("")
        lines.append(notes.suggested_follow_up or "_None._")
        lines.append("")

        lines.append("---")
        provider = "mock provider" if notes.used_mock else f"`{notes.model_name}`"
        lines.append(
            f"_Confidence: {int(notes.confidence * 100)}% · Generated by {provider}._"
        )
    else:
        lines.append("_Notes have not been generated yet._")

    if meeting.transcript:
        lines.append("")
        lines.append("## Transcript")
        lines.append("")
        lines.append("```")
        lines.append(meeting.transcript.strip())
        lines.append("```")

    markdown = "\n".join(lines).rstrip() + "\n"
    filename = f"{_slugify(meeting.title)}.md"
    return MarkdownExport(meeting_id=meeting.id, filename=filename, markdown=markdown)
